#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
#xmodmap "/home/simon/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# Not needed since network managmenet is system-wide
# nm-applet &
# Not needed either as this is a server now
#xfce4-power-manager &
# The server runs via remote vnc, so wallpaper is not needed
#fbsetbg -l
fbsetroot -solid navy

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/simon/.fluxbox/log"
